sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t justin0979/docker-react .

script:
  - docker run -e CI=true justin0979/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-519144714901"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
