sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t justin0979/docker-react .

script:
  - docker run -e CI=true justin0979/docker-react npm run test
